services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: unless-stopped
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env

  minio:
    container_name: minio-s3
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    env_file:
      - .env

volumes:
    pgdata:
    minio_storage: