global:
  scrape_interval: 15s  # How often Prometheus scrapes data

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]  # FastAPI container name in Docker