"""Create AnalyticsModule and ModuleEvent tables + connections

Revision ID: cbc91f2ce4d6
Revises: 95141327ee25
Create Date: 2025-03-09 17:26:36.273243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbc91f2ce4d6"
down_revision: Union[str, None] = "95141327ee25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules_analytics_module",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("module_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules_analytics_module")),
    )
    op.create_table(
        "module_device_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices_device.id"],
            name=op.f("fk_module_device_association_device_id_devices_device"),
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules_analytics_module.id"],
            name=op.f("fk_module_device_association_module_id_modules_analytics_module"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_module_device_association")),
    )
    op.create_table(
        "modules_module_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_path", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), server_default="MEDIUM", nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices_device.id"],
            name=op.f("fk_modules_module_event_device_id_devices_device"),
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules_analytics_module.id"],
            name=op.f("fk_modules_module_event_module_id_modules_analytics_module"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules_module_event")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modules_module_event")
    op.drop_table("module_device_association")
    op.drop_table("modules_analytics_module")
    # ### end Alembic commands ###
