"""Create DeviceFileArchive table

Revision ID: 95141327ee25
Revises: cd1c046a198d
Create Date: 2025-03-08 21:58:55.842995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95141327ee25"
down_revision: Union[str, None] = "cd1c046a198d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices_device_file_archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("filepath", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("timestamp_start", sa.DateTime(), nullable=False),
        sa.Column("timestamp_end", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices_device.id"],
            name=op.f("fk_devices_device_file_archive_device_id_devices_device"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices_device_file_archive")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices_device_file_archive")
    # ### end Alembic commands ###
