"""Create Device table

Revision ID: cd1c046a198d
Revises:
Create Date: 2025-03-06 23:55:48.114045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd1c046a198d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices_device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum("CAMERA", "MICROPHONE", name="devicetype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("additional_settings", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices_device")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices_device")
    sa.Enum("CAMERA", "MICROPHONE", name="devicetype").drop(op.get_bind())
    # ### end Alembic commands ###
